riddles/urls.py
from django.conf.urls import url

from . import views

app_name = 'riddles'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^([0-9]+)/$', views.detail, name='detail'),
    url(r'^([0-9]+)/answer/$', views.answer, name='answer'),
    url(r'^register/$', views.RegisterFormView.as_view()),
    url(r'^login/$', views.LoginFormView.as_view()),
    url(r'^logout/$', views.LogoutView.as_view()),
    url(r'^password-change/', views.PasswordChangeView.as_view()),
    url(r'^$', views.index, name='index'),
    url(r'^([0-9]+)/$', views.detail, name='detail'),
    url(r'^([0-9]+)/answer/$', views.answer, name='answer'),
    # отправка сообщения
    url(r'^([0-9]+)/post/$', views.post, name='post'),
    # отправка списка сообщений
    url(r'^([0-9]+)/msg_list/$',
        views.msg_list,
        name='msg_list'),
    # отправка оценки
    url(r'^([0-9]+)/post_mark/$',
        views.post_mark,
        name='post_mark'),
# средняя оценка
    url(r'^([0-9]+)/get_mark/$',
        views.get_mark,
    name='get_mark'),

]

riddles/models.py
from django.db import models

# Create your models here.

class Riddle(models.Model):
    riddle_text = models.CharField(max_length=255)
    pub_date = models.DateTimeField('date published')


class Option(models.Model):
    riddle = models.ForeignKey(Riddle, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    correct = models.BooleanField(default=False)

# встроенная модель пользователя
# нужна для авторов сообщений
from django.contrib.auth.models import User
# тип "временнАя зона" для получения текущего времени
from django.utils import timezone
...
class Message(models.Model):
    chat = models.ForeignKey(
        Riddle,
        verbose_name='Чат под загадкой',
        on_delete=models.CASCADE)
    author = models.ForeignKey(
        User,
        verbose_name='Пользователь', on_delete=models.CASCADE)
    message = models.TextField('Сообщение')
    pub_date = models.DateTimeField(
        'Дата сообщения',
        default=timezone.now)

class Mark(models.Model):
    riddle = models.ForeignKey(
        Riddle,
        verbose_name='Загадка',
        on_delete=models.CASCADE)
    author = models.ForeignKey(
        User,
        verbose_name='Пользователь', on_delete=models.CASCADE)
    mark = models.IntegerField(
        verbose_name='Оценка')
    pub_date = models.DateTimeField(
        'Дата оценки',
        default=timezone.now)

riddles/templates/answer.html
{% extends 'base.html' %}
{% block main %}
<h4 class="card-title">{{ riddle.riddle_text }}</h4>
{% if error_message %}
    <p class="alert alert-danger">
        <strong>{{ error_message }}</strong>
    </p>
{% endif %}
<form action="answer/" method="post">
    {% csrf_token %}
    {% for option in riddle.option_set.all %}
        <input type="radio" name="option"
            id="option{{ forloop.counter }}"
            value="{{ option.id }}"/>
        <label for="option{{ forloop.counter }}">
            {{ option.text }}
        </label><br>
    {% endfor %}
    <input type="submit" value="Answer"/>
</form>
    <hr>
<h4>Chat</h4>
{% if user.is_authenticated %}
    <form action="post/" method="post">
    {% csrf_token %}
    <div class="input-group mb-3">
      <input type="text"
             class="form-control"
             placeholder="Your message"
             name="message"/>
      <div class="input-group-append">
        <input class="btn btn-success"
                type="submit"
                value="Send"/>
      </div>
    </div>
</form>
{% endif %}
<div id="history">
    {% for message in latest_messages %}
        <div class="card">
        <div class="card-body">
            <strong>
                {{ message.author.username }}
            </strong>
            <br/>
            <em>
                {{ message.pub_date|date:'Y-m-d H:i:s' }}
            </em>
            <br/>
            {{ message.message }}
        </div>
        </div>
        <br/>
    {% endfor %}
</div>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js">
</script>
<script>
function send_msg_update_request(){
    $.get("msg_list/",{},parse_msg_update_response);
}
function parse_msg_update_response(data, success){
    //alert(data);
    res = JSON.parse(data);
    res_str = "";
    for(i=0;i<res.length;i++){
        // HTML-код вставляемых блоков с сообщениями
        // скопирован выше - тот, что выводится
        // при загрузке страницы
        res_str += '<div class="card">\n' +
            '        <div class="card-body">\n' +
            '            <strong>\n' +
            '                '+res[i].author__username+'\n' +
            '            </strong>\n' +
            '            <br/>\n' +
            '            <em>\n' +
            '                '+res[i].pub_date+'\n' +
            '            </em>\n' +
            '            <br/>\n' +
            '            '+res[i].message+'\n' +
            '        </div>\n' +
            '        </div>\n' +
            '        <br/>'
    }
    $("#history").html(res_str);
}
setInterval(send_msg_update_request, 5000);
</script>
<hr>
<h4>Rating</h4>
    <p>Average rating:
        <span id="avg_mark_span">
            {{ avg_mark }}
        </span>
    </p>
{% if user.is_authenticated %}
    {% if already_rated_by_user <= 0 or already_rated_by_user ==  None %}
        <form action="post_mark/" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm text-center">
                    <input name="mark"
                           type="radio"
                           value="1"/> 1
                </div>
                <div class="col-sm text-center">
                    <input name="mark"
                           type="radio"
                           value="2"/> 2
                </div>
                <div class="col-sm text-center">
                    <input name="mark"
                           type="radio"
                           value="3"/> 3
                </div>
                <div class="col-sm text-center">
                    <input name="mark"
                           type="radio"
                           value="4"/> 4
                </div>
                <div class="col-sm text-center">
                    <input name="mark"
                           type="radio"
                           value="5"/> 5
                </div>
                <div class="col-sm text-center">
                    <input class="btn btn-success"
                        type="submit"
                        value="Send mark"/>
                </div>
            </div>
        </form>
        {% else %}
        Your rating: {{ user_rating }}
    {% endif %}

{% endif %}
<hr>
<h4>Chat</h4>
<script>
function send_msg_update_request(){
    $.get("msg_list/",{},parse_msg_update_response);
    $.get("get_mark/",{},parse_mark_update_response);
}
//старая функция
function parse_msg_update_response(data, success){
...
}
function parse_mark_update_response(data, success){
    res = JSON.parse(data);
    $("#avg_mark_span").html(res["mark__avg"].toFixed(1));
}
setInterval(send_msg_update_request, 5000);
</script>


{% endblock %}

riddles/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet"
href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <title>Riddles</title>
</head>
<body>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            <h1 class="mt-2">Riddles</h1>
            {% if user.is_authenticated %}
                <p class="text-right">
                    Hello, {{ user.username }}!
                    <a href="/riddles/logout">Log out</a> |
                    <a href="/riddles/password-change">
                        Change password
                    </a>
                </p>
            {% else %}
                <p class="text-right">
                    <a href="/riddles/login">Log in</a> |
                    <a href="/riddles/register">Register</a>
                </p>
            {% endif %}
            <hr class="mt-0 mb-4">
            <div class="card">
                <div class="card-body">
                    {% block main %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

riddles/templates/index.html
{% extends 'base.html' %}
{% block main %}
    <h4 class="card-title">Available Riddles</h4>
    {% if message %}
        <p class="alert alert-success">
            <strong>{{ message }}</strong>
        </p>
    {% endif %}
    {% if latest_riddles %}
        <ul>
            {% for riddle in latest_riddles %}
                <li>
                    <a href="/riddles/{{ riddle.id }}/">
                        {{ riddle.riddle_text }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No riddles are available right now.</p>
    {% endif %}
{% endblock %}